'use strict';

const { state } = require('../store');

/**
 * Bearer token format: "token-<userId>"
 * Generated by POST /api/auth/login
 */
function requireAuth(req, res, next) {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Unauthorized' });
  }
  const token = authHeader.slice(7);
  const userId = token.replace('token-', '');
  const user = state.users.find(u => u.id === userId);
  if (!user) {
    return res.status(401).json({ error: 'Unauthorized' });
  }
  req.user = user;
  next();
}

module.exports = { requireAuth };
